services:
  app-ui:
    build: .
    image: app-ui
    container_name: app-ui
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    # stdin_open: true # Equivalent to -it, keeps STDIN open
    tty: true # Equivalent to -it, allocates a pseudo-TTY
    command: bash # Starts a bash shell when the container runs
